use demo;
use wzag;

-- 20090330
ALTER TABLE CURRENCIES
CHANGE COLUMN EXCH_RATE_TO_1_USD EXCH_RATE_TO_1_HOME float;

-- 20090331

ALTER TABLE HOTELRESERVATIONS
ADD CONF varchar(40);

ALTER TABLE VEHICLERESERVATIONS
ADD CONF varchar(40);

ALTER TABLE HOTELRESERVATIONS
ADD PURPOSE varchar(240);
ALTER TABLE VEHICLERESERVATIONS
ADD PURPOSE varchar(240);
ALTER TABLE OTHERRESERVATIONS
ADD PURPOSE varchar(240);
ALTER TABLE FLIGHTRESERVATIONS
ADD PURPOSE varchar(240);

ALTER TABLE HOTELRESERVATIONS
ADD FOLLOWUP bit;
ALTER TABLE VEHICLERESERVATIONS
ADD FOLLOWUP bit;
ALTER TABLE OTHERRESERVATIONS
ADD FOLLOWUP bit;
ALTER TABLE FLIGHTRESERVATIONS
ADD FOLLOWUP bit;

ALTER TABLE SOSCOVERAGES
CHANGE COLUMN COVERED PERSONAL_COVERAGE bit;
ALTER TABLE SOSCOVERAGES
ADD CARD_NUMBER varchar(40);

-- 20090415
ALTER TABLE HOTELRESERVATIONS
MODIFY FOLLOWUP bit NOT NULL DEFAULT FALSE;
ALTER TABLE VEHICLERESERVATIONS
MODIFY FOLLOWUP bit NOT NULL DEFAULT FALSE;
ALTER TABLE OTHERRESERVATIONS
MODIFY FOLLOWUP bit NOT NULL DEFAULT FALSE;
ALTER TABLE FLIGHTRESERVATIONS
MODIFY FOLLOWUP bit NOT NULL DEFAULT FALSE;

